# Site settings
title: William Hexberg
email: whexberg@gmail.com
description: A blog about my favorite web conferences.
url: "http://whexberg.github.io" # the base hostname & protocol for your site
twitter_username: whexberg
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: "" # and empty string here means all files in the project
      type: "posts" #previously 'post' in jekyl 2.2.
    values:
      author: "William Hexberg"
      layout: "post"
      category: conferences
      comments: true
  -
    scope:
      path: "" # and empty string here means all files in the project
      type: "drafts" #previously 'post' in jekyl 2.2.
    values:
      author: "William Hexberg"
      layout: "post"
      category: conferences
  -
    scope:
      path: "" # and empty string here means all files in the project
      type: "pages" #previously 'post' in jekyl 2.2.
    values:
      layout: "page"